### ISSUE TITLE
call 文件夹下    Sample.php中  HttpUtils.ParseUrl是怎么起作用的？

### ISSUE THREAD

**Issue by xiaolongsoft** [sbzhu/weworkapi_php#17]
我php用的不多，知道些基本语法。
PHP中调用静态是用::符号的

但是这个例子中 HttpUtils 并没有直接声明，我再别的文件也没找到，他是怎么起作用的？

**Comment by sbzhu** [comment]
你好，那个只是伪代码~

**Comment by SmallOyster** [comment]
> 你好，那个只是伪代码~

您好，那我想问一下sample文件中的setResponse是大概怎么思路？
是直接curl还是……？
