### ISSUE TITLE
callback文件夹中一些类的构造函数建议改为__construct

### ISSUE THREAD

**Issue by xiaoyouxi01** [sbzhu/weworkapi_php#2]
我在PHP7上测试服务器验证，一直不成功。
后来发现，是由于构造函数的问题，返回了一些PHP报错信息，导致验证不成功。
callback文件夹中，一些类的构造函数采用跟类名相同的命名方式，而不是用__construct。

例如下面这个public function WXBizMsgCrypt($token, $encodingAesKey, $Corpid)

`class WXBizMsgCrypt
{
	private $m_sToken;
	private $m_sEncodingAesKey;
	private $m_sCorpid;

	/**
	 * 构造函数
	 * @param $token string 公众平台上，开发者设置的token
	 * @param $encodingAesKey string 公众平台上，开发者设置的EncodingAESKey
	 * @param $Corpid string 公众平台的Corpid
	 */
	public function WXBizMsgCrypt($token, $encodingAesKey, $Corpid)
	{
		$this->m_sToken = $token;
		$this->m_sEncodingAesKey = $encodingAesKey;
		$this->m_sCorpid = $Corpid;
	}
}`

建议修改下~

**Comment by sbzhu** [comment]
oh~,callback这块是之前同事写的，写成c++风格了哈哈。。谢谢~~

**Comment by sbzhu** [comment]
已经改了，再次谢谢@xiaoyouxi01
