### ISSUE TITLE
提交一个BUG，该BUG会导致创建成员时，name字段强制转换为UTF8编码

### ISSUE THREAD

**Issue by ttdms** [sbzhu/weworkapi_php#21]
LIB目录helper.php第62行
`$strPOST = json_encode($param);`
json_encode会强制把中文转换成UTF8编码，导致创建成员时，提交上去的都是UTF8编码，变成不可读
[点击看图](http://v.mgbubu.com/20181107164814.png)
PHP5.4新增了一个选项JSON_UNESCAPED_UNICODE，应该改成
`$strPOST = json_encode($param,JSON_UNESCAPED_UNICODE);`
这样创建成员测试正常

**Comment by sbzhu** [comment]
多谢！
