### ISSUE TITLE
access_token缓存机制造成多个应用发送信息失败

### ISSUE THREAD

**Issue by moonscu** [sbzhu/weworkapi_php#22]
大神，由于access_token全局缓存了，造成多个切换应用发送消息时会报错，请问有解决的办法吗？

**Comment by sbzhu** [comment]
全局缓存为啥会造成失败？失败返回包是什么？

**Comment by moonscu** [comment]
失败返回的包就是301002。难道是我的调用方法错了吗？
我自己封装了一个类
`
<?php
namespace Wechat\Vendor;
include_once dirname(__DIR__) . "/ORG/weworkapi_php/api/src/CorpAPI.class.php";
include_once dirname(__DIR__) . "/ORG/weworkapi_php/api/src/ServiceCorpAPI.class.php";
include_once dirname(__DIR__) . "/ORG/weworkapi_php/api/src/ServiceProviderAPI.class.php";
class OAuth {
	private $API = null;
        private $config = null;
	public function __construct() {
		$CONFIG = C('WWAUTH');//引入配置
		$this->config = $CONFIG;
		$this->API = new \CorpAPI($this->config['CORPID'], $this->config['Secret']);
		$this->config = $CONFIG;
	}
        /**
	 * 发送消息
	 * @param string $content 消息内容
	 * @param array $users 用户列表
	 * @param string $agent 消息接收程序
	 */
	public function sendTextMessage(string $content, array $users, $agent = 'subtask') {
		$message = new \Message();
		$message->messageContent = new \TextMessageContent($content);
		$message->agentid = $this->config['AgentId'][$agent];
		$message->touser = $users;
		return $this->API->MessageSend($message);
	}
｝
`
配置文件
`
	'WWAUTH' => array(
		'CORPID' => "",
		'AgentId' => [
			'subtask' => "1000027",
			'bill' => "1000045"],
		'Secret' => "",
	),
`

调用的时候用下面这个方法
`
	/**
	 * 发送通知
	 * @param string $message 消息内容
	 * @param array $users 用户列表
	 * @param string $agent 接收消息的程序
	 */
	protected function notice($message, $users, $agent) {
		$OAuth = new \Wechat\Vendor\OAuth;
		$OAuth->sendTextMessage($message, $users, $agent);
	}
`

但每次调用都会默认使用第一个应用的appid，用第2个应用的appid时，就会出错。类的封闭是按你给的example写的呀。

**Comment by moonscu** [comment]
失败返回的包就是301002。难道是我的调用方法错了吗？
我自己封装了一个类
```<?php
namespace Wechat\Vendor;
include_once dirname(__DIR__) . "/ORG/weworkapi_php/api/src/CorpAPI.class.php";
include_once dirname(__DIR__) . "/ORG/weworkapi_php/api/src/ServiceCorpAPI.class.php";
include_once dirname(__DIR__) . "/ORG/weworkapi_php/api/src/ServiceProviderAPI.class.php";
class OAuth {
	private $API = null;
        private $config = null;
	public function __construct() {
		$CONFIG = C('WWAUTH');//引入配置
		$this->config = $CONFIG;
		$this->API = new \CorpAPI($this->config['CORPID'], $this->config['Secret']);
		$this->config = $CONFIG;
	}
        /**
	 * 发送消息
	 * @param string $content 消息内容
	 * @param array $users 用户列表
	 * @param string $agent 消息接收程序
	 */
	public function sendTextMessage(string $content, array $users, $agent = 'subtask') {
		$message = new \Message();
		$message->messageContent = new \TextMessageContent($content);
		$message->agentid = $this->config['AgentId'][$agent];
		$message->touser = $users;
		return $this->API->MessageSend($message);
	}
｝```
配置文件
`
	'WWAUTH' => array(
		'CORPID' => "",
		'AgentId' => [
			'subtask' => "1000027",
			'bill' => "1000045"],
		'Secret' => "",
	),
`

调用的时候用下面这个方法
`
	/**
	 * 发送通知
	 * @param string $message 消息内容
	 * @param array $users 用户列表
	 * @param string $agent 接收消息的程序
	 */
	protected function notice($message, $users, $agent) {
		$OAuth = new \Wechat\Vendor\OAuth;
		$OAuth->sendTextMessage($message, $users, $agent);
	}
`

但每次调用都会默认使用第一个应用的appid，用第2个应用的appid时，就会出错。类的封闭是按你给的example写的呀。

**Comment by moonscu** [comment]
我知道原因了，因为我在配置项里面只保存了一个app的secret，所以产生的token只有一个，另一个app调用的时候就会出错。
