### ISSUE TITLE
请问你把accessToken存在哪儿了？

### ISSUE THREAD

**Issue by hi500** [sbzhu/weworkapi_php#3]
accessToken刷新每天是有次数限制的，我看不出来你的代码中如何做accessToken缓存的

**Comment by xiaoyouxi01** [comment]
我也挺想知道这个的。。

官网文档中下载的示例代码里，倒是有缓存的，是存在本地一个文件中。

GitHub上的代码，我也看不出来缓存。。。

**Comment by sbzhu** [comment]
是以类里的一个变量存的
比如api/src/CorpAPI.class.php 里的accessToken变量，
在类的生命周期里，这个accessToken都是存在的，而且使用时发现token过期，会自动刷新 token。
所以，使用时，只需要实例化一次CorpAPI类，不要析构它，就可一直用它调函数，不用关心 token。
```
$api = new CorpAPI(corpid, corpsecret);
$api->dosomething()
$api->dosomething()
$api->dosomething()
....
```

**Comment by walkonthemarz** [comment]
@sbzhu 那你的这个accessToken缓存也仅仅只在当前请求中有效，如果一个新的请求过来的话，你还是重新获取了一遍token，并没有实现多个请求之间共享一个token

**Comment by walkonthemarz** [comment]
而且看你的类里面把token设成了private,我都没法把token缓存到redis，想到的一个办法也许可以把整个类serialize以后存到redis，或者你能把token设成public或添加一个set方法 @sbzhu

**Comment by sbzhu** [comment]
@walkonthemarz 只要保证全局只实例化一个这个类，即实现了共享token，当然，你用redis或者文件来缓存，也是可以的
