### ISSUE TITLE
call文件夹下的Sample.php，里面的setResponce的实现思路是？

### ISSUE THREAD

**Issue by SmallOyster** [sbzhu/weworkapi_php#31]
emmm我的意思是
这个函数设计来是包装为一个更直接的curl助手函数还是其他solution？

谢谢WXG大佬的关注！

**Comment by xiaohero** [comment]
就是echo让你原文输出去，这可能是java的风格

**Comment by SmallOyster** [comment]
> 就是echo让你原文输出去，这可能是java的风格

哦……好的谢谢！
