### ISSUE TITLE
关于JS-SDK：jsapi_ticket的缓存跟token的缓存一样吗？另外，可否增加生成签名？

### ISSUE THREAD

**Issue by xiaoyouxi01** [sbzhu/weworkapi_php#7]
在CorpAPI.class.php中看到获取jsapi_ticket的函数，请问下jsapi_ticket的缓存跟token的缓存一样吗？

    /**
     * @brief JsApiTicketGet : 获取jsapi_ticket
     *
     * @link https://work.weixin.qq.com/api/doc#10029/获取jsapi_ticket
     *
     * @return : string ticket
     */
    public function JsApiTicketGet()
    {
        self::_HttpCall(self::GET_JSAPI_TICKET, 'GET', null); 
        return $this->rspJson["ticket"];
    }

另外，可否在SDK中增加“获取自定义应用的签名对象”的代码？
api\examples\JsApiTest中只有获取jsapi_ticket，最好可以直接生成JSAPI签名，一步到位。

我在开发文档这个页面有看到这个函数function getSignPackage()，但是在SDK里没找到这个。。
https://work.weixin.qq.com/api/doc#10520/网页开发

**Comment by sbzhu** [comment]
1.  获取jsapi_ticket的函数，请问下jsapi_ticket的缓存跟token的缓存一样吗？
